[package]
name = "cosmic-settings"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
rust-version = "1.65.0"

[dependencies]
apply = "0.3.0"
derive_setters = "0.1.5"
i18n-embed-fl = "0.6.5"
once_cell = "1.17.0"
regex = "1.7.1"
rust-embed = "6.4.2"
slotmap = "1.0.6"

[dependencies.i18n-embed]
version = "0.13.8"
features = ["fluent-system", "desktop-requester"]

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
branch = "settings-improv"
default-features = false
features = ["debug", "winit", "dyrend"]