[workspace]
members = ["app", "page", "pages/*"]
default-members = ["app"]

[workspace.dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
rev = "f06a81c"
default-features = false
features = ["debug", "wayland", "tokio"]

[workspace.dependencies.cosmic-config]
git = "https://github.com/pop-os/libcosmic"
rev = "f06a81c"