[package]
name = "cosmic-settings-time"
version = "0.1.0"
edition = "2021"

[dependencies]
icu_calendar = "1.5.2"
icu_timezone = "1.5.0"
timedate-zbus = "0.1.0"

[dependencies.zbus]
version = "3.15.2"
default-features = false
features = ["tokio"]
